src/mailsender/urls.py
from django.urls import path
from . import views

app_name = "sender"

urlpatterns = [
    # path('history/', views.history, name="list"),
    path('', views.form, name="form"),
    # path('<str:broadcast>', views.form, name="form"),
    # path('success/<str:broadcast>', views.success, name="success"),
]

src/mailtemplates/urls.py
from django.urls import path, include
from . import views

app_name="templates"
urlpatterns = [
    path('', views.template_form, name="home"),
    # path('categories/', views.categories, name="categories"),
    path('categories/form/', views.category_form, name="category.form"),
    path('categories/form/<slug:category>', views.category_form, name="category.form"),
    path('categories/delete/<str:category_id>', views.deleteCategory, name="category.delete"),
    path('form/', views.template_form, name="form"),
    path('form/<slug:slug>', views.template_form, name="form"),
    path('<slug:slug>', views.template_detail, name="detail"),
    path('delete/<str:template_id>', views.delete, name="delete")
    ]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("import/", include("importer.urls")),
    path("models/", include("mailtemplates.urls")),
    path("sender/", include("mailsender.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("agendas/", include("agendas.urls")),
    path("", views.home),
    # Forgot password URLS
    path(
        "reset-password/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "reset-password/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        views.password_updated,
        name="password_reset_complete",
    ),
    # Change passowrd URLs
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path("change-password/done/", views.password_updated, name="password_change_done"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/mailtemplates/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models.functions import datetime


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name="Nombre")
    slug = models.SlugField(verbose_name="Slug de la categoría (URL amigable)")

    def __str__(self):
        return self.title

class MailTemplate(models.Model):
    year = models.year = models.IntegerField(
        default=datetime.timezone.now().year,
        validators=[MinValueValidator(1970), MaxValueValidator(9999)],
        verbose_name="Año",
    )
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name="Categoría",
    )
    title = models.CharField(
        max_length=100, default="", blank=True, verbose_name="Título"
    )
    slug = models.SlugField(default="", unique=True, verbose_name="URL")
    subject = models.TextField(default="", blank=True, verbose_name="Asunto")
    content = models.TextField(
        blank=True, default="", verbose_name="Cuerpo del mensaje"
    )

    creation_date = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

src/mailtemplates/forms.py
from django import forms
from .models import Category, MailTemplate
from django_summernote.widgets import SummernoteWidget
from django.utils.text import slugify

class CategoryForm(forms.ModelForm):
     class Meta:
         model = Category
         fields = '__all__'

class TemplateForm(forms.ModelForm):
    new_category_title = forms.CharField(required=False, label="Nueva categoría")
    slug = forms.CharField(required=False)

    class Meta:
        model = MailTemplate
        fields = ["title", "year", "category", "new_category_title", "subject", "content", "slug"]
        widgets = {
        'content': SummernoteWidget(),
        }

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        category = cleaned_data.get("category")
        new_category_title = cleaned_data.get("new_category_title")
        year = cleaned_data.get("year")

        # If a new category title is provided, create a new category and use it for the agenda
        if title:
            if Category.objects.filter(title=title).exists():
                self.add_error(
                    "title", "Ya existe una agenda con este nombre."
                )
            elif Category.objects.filter(slug=slugify(title)).exists():
                self.add_error(
                    "title",
                    "Ya existe una agenda con el slug generado a partir de este nombre.",
                )
            else:
                slug = slugify(f'{category}-{year}-{title}')
                cleaned_data["slug"] = slug

        # If a new category title is provided, create a new category and use it for the agenda
        if new_category_title and not category:
            if Category.objects.filter(title=new_category_title).exists():
                self.add_error(
                    "new_category_title", "Ya existe una categoria con este nombre."
                )
            elif Category.objects.filter(slug=slugify(new_category_title)).exists():
                self.add_error(
                    "new_category_title",
                    "Ya existe una categoria con el slug generado a partir de este nombre.",
                )
            else:
                slug = slugify(new_category_title)
                category = Category.objects.create(title=new_category_title, slug=slug)
                cleaned_data["category"] = category

        # If no category is selected and no new category title is provided, raise a validation error
        elif not category:
            self.add_error(
                "category", "Please select an existing category or create a new one."
            )

        return cleaned_data

src/mailtemplates/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, redirect
from .models import MailTemplate, Category
from . import forms
from django.core import serializers
from django.forms import model_to_dict
import logging

# Get an instance of a logger
logger = logging.getLogger("logging.StreamHandler")


@staff_member_required(login_url="accounts:staff_only")
def deleteCategory(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    return redirect("templates:home")


@staff_member_required(login_url="accounts:staff_only")
def delete(request, template_id):
    template = MailTemplate.objects.get(id=template_id)
    template.delete()
    return redirect("templates:home")


# def categories(request):
#     categories = Category.objects.all()
#     return render(
#         request, "mailtemplates/categories/list.html", {"categories": categories}
#     )


def template_list(request):
    category = request.GET.get("category") or None
    if category:
        category = Category.objects.get(slug=category)
        templates = MailTemplate.objects.filter(category=category.id)
    else:
        templates = MailTemplate.objects.all()
    return render(
        request,
        "mailtemplates/list.html",
        {"templates": templates, "category": category},
    )


@staff_member_required(login_url="accounts:staff_only")
def template_detail(request, slug):
    template = MailTemplate.objects.get(slug=slug)
    menu_items = [
        {
            "label": cat,
            "value": [ag for ag in MailTemplate.objects.filter(category=cat.id)],
        }
        for cat in Category.objects.all()
    ]
    return render(
        request,
        "mailtemplates/detail.html",
        {
            "template": template,
            "menu_items": menu_items,
            "menu_title": "Modelos",
            "menu_type": "plantilla",
        },
    )


@staff_member_required(login_url="accounts:staff_only")
def template_form(request, slug=""):
    template = MailTemplate.objects.get(slug=slug) if slug else None
    menu_items = [
        {
            "label": cat,
            "value": [ag for ag in MailTemplate.objects.filter(category=cat.id)],
        }
        for cat in Category.objects.all()
    ]
    if request.method == "POST":
        logger.info("POST form")
        form = forms.TemplateForm(request.POST or None, instance=template)
        logger.info(form)
        if form.is_valid():
            template_instance = form.save(commit=False)
            template_instance.save()
            return redirect("templates:detail", slug=template_instance.slug)
    else:
        form = forms.TemplateForm(initial=model_to_dict(template) if template else None)
    return render(
        request,
        "mailtemplates/form.html",
        {
            "template": template,
            "form": form,
            "menu_items": menu_items,
            "menu_title": "Modelos",
            "menu_type": "plantilla",
        },
    )


@staff_member_required(login_url="accounts:staff_only")
def category_form(request, category=""):
    category = Category.objects.get(slug=category) if category else None
    if request.method == "POST":
        form = forms.CategoryForm(request.POST or None, instance=category)
        if form.is_valid():
            category_instance = form.save(commit=False)
            category_instance.save()
            return redirect("templates:home")
    else:
        form = forms.CategoryForm(initial=model_to_dict(category) if category else None)
    return render(
        request,
        "mailtemplates/categories/form.html",
        {"category": category, "form": form},
    )

src/mailtemplates/templates/mailtemplates/detail.html
{% extends 'base.html' %}{% block content %}

<div class="container shadow rounded p-4 my-4">
    <div class="row">
        <h3 class="col-auto mx-2">{{template.title}}</h3>
        <p class="col-auto mx-2 my-auto">{{template.category}}</p>
        <p class="col-auto mx-2 my-auto">{{template.year}}</p>
        <p class="col-auto mx-2 my-auto">
            Modelo creado el {{template.creation_date}}
        </p>

    <div class="col-auto ms-auto my-auto">
      <form
        class="form-inline"
        action="{% url 'templates:form' slug=template.slug %}"
      >
        <button class="btn shadow ml-auto">
          <i class="bi bi-pencil-square text-success"></i>&nbsp;&nbsp;Editar
          Modelo
        </button>
            </form>
        </div>
    </div>
    <div class="subject p-3 my-4">
        <div class="content rounded p-3 card col-12 d-inline-block">
            <a class="strong text-decoration-none">Asunto: </a>{{template.subject}}
        </div>
        <div class="content rounded p-3 card">{{template.content|safe}}</div>
    </div>

  <form
    class="form-inline col-12 col-lg-4 mx-auto mb-2 mb-lg-0"
    action="{% url 'sender:form' %}"
    method="POST"
  >
    {% csrf_token %}
    <input type="hidden" name="imported" value="Importar" />
    <input type="hidden" name="template" value="{{template.slug}}" />
    <button class="btn shadow col-12">
      <i class="bi bi-envelope text-success"></i>&nbsp;&nbsp;Broadcast
    </button>
    </form>

    {% endblock content %}
</div>

src/mailtemplates/templates/mailtemplates/form.html
{% extends 'base.html' %} {% block content %}
<div class="container shadow my-4 p-4">
  {%if template %}
  <h2>Editar modelo</h2>
  <a
    href="#"
    onclick="if(confirm('¡Atención! ¿Desea borrar el modelo {{template.title}}?'))
{location.href='{% url 'templates:delete' template_id=template.id %}'}"
    >Borrar modelo</a
  >
  {% else %}
  <h2>Crear modelo</h2>
  {% endif %}
  <form
    class="site-form"
    action="
        {% if template %} 
        {% url 'templates:form' slug=template.slug %}
        {% else %}{% url 'templates:form' %}
        {% endif %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% include 'base_form.html' %} {{ form1.content }}
  </form>
</div>
<!-- <script src={ % static "js/slugify.js" %}></script> -->
{% endblock content %}

src/mailtemplates/templates/mailtemplates/list.html
{% extends 'base.html' %} {% block content %}{% load django_bootstrap_icons %}

<div class="container p-4 my-4 shadow rounded">
    {% if category %}
    <h2 class="my-3 display-4">Plantillas en categoría: {{category.title}}</h2>
    {% else %}
    <h2 class="my-3 display-4">Todas las plantillas</h2>
    {% endif %}{% if templates %} {% for template in templates %}
    <div class="template form-inline">
        <div class="dropdown">
            <a class="dropdown-toggle badge" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% bs_icon 'three-dots-vertical' extra_classes='text-primary mx-2'%}</a>
            <ul class="dropdown-menu text-center" aria-labelledby="navbarDropdownMenuLink">
                <li class="btn" onclick="location.href='{% url 'templates:detail' slug=template.slug %}';">Ver {% bs_icon 'eye' extra_classes='text-primary mx-2'%}</li>
                <li class="btn" onclick="location.href='{% url 'templates:form' slug=template.slug %}';">Editar {% bs_icon 'pencil-square' extra_classes='text-success mx-2'%}</li>
                <li class="btn" onclick="if(confirm('¡Atención! ¿Desea borrar la categoria {{template.title}} y plantillas asociadas?'))
            {location.href='{% url 'templates:delete' template_id=template.id %}'; alert('agenda borrada');}">Borrar {% bs_icon 'trash' extra_classes='text-danger mx-2'%}</li>
            </ul>
        </div>
        <h2><a href="{% url 'templates:detail' slug=template.slug %}">{{template.title}}</a></h2>
    </div>
    {% endfor %} {% else %} No se han encontrado plantillas {% endif %}
    <div class="form-group row">
        <form class="form-inline col-auto mx-auto mt-3" action="{% url 'templates:form' %}">
            <input type="hidden" name="category" value="{{category.slug}}">
            <button class="btn  shadow col-12 mx-3">{% bs_icon 'plus-circle-fill' extra_classes='text-success'%}&nbsp;&nbsp;Nueva Plantilla</button>
        </form>
    </div>
</div>
{% endblock %}