src/accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"

urlpatterns = [
    path("login", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("signin", views.register, name="register"),
    path("staff_only", views.staff_only, name="staff_only"),
    path("password_updated", views.password_updated, name="password_updated"),
]

src/agendas/urls.py
from django.urls import path, include
from . import views

app_name = "agendas"
urlpatterns = [
    # path("agendas/", views.get_agendas, name="list"),
    path("", views.agenda_detail, name="home"),
    # path("categories/", views.categories, name="categoreis"),
    path("categories/form/", views.category_form, name="category.form"),
    path("categories/form/<slug:category>", views.category_form, name="category.form"),
    path(
        "categories/delete/<str:category_id>",
        views.deleteCategory,
        name="category.delete",
    ),
    path("form/", views.agenda_form, name="form"),
    path("form/<slug:slug>", views.agenda_form, name="form"),
    path("<slug:slug>", views.agenda_detail, name="detail"),
    path(
        "<slug:slug>/import", include(("importer.urls", "home"), namespace="importer")
    ),
    path("<slug:slug>/contacts/", include("contacts.urls")),
    path("delete/<str:agenda_id>", views.delete, name="delete"),
]

src/mailsender/urls.py
from django.urls import path
from . import views

app_name = "sender"

urlpatterns = [
    # path('history/', views.history, name="list"),
    path('', views.form, name="form"),
    # path('<str:broadcast>', views.form, name="form"),
    # path('success/<str:broadcast>', views.success, name="success"),
]

src/mailtemplates/urls.py
from django.urls import path, include
from . import views

app_name="templates"
urlpatterns = [
    path('', views.template_form, name="home"),
    # path('categories/', views.categories, name="categories"),
    path('categories/form/', views.category_form, name="category.form"),
    path('categories/form/<slug:category>', views.category_form, name="category.form"),
    path('categories/delete/<str:category_id>', views.deleteCategory, name="category.delete"),
    path('form/', views.template_form, name="form"),
    path('form/<slug:slug>', views.template_form, name="form"),
    path('<slug:slug>', views.template_detail, name="detail"),
    path('delete/<str:template_id>', views.delete, name="delete")
    ]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("import/", include("importer.urls")),
    path("models/", include("mailtemplates.urls")),
    path("sender/", include("mailsender.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("agendas/", include("agendas.urls")),
    path("", views.home),
    # Forgot password URLS
    path(
        "reset-password/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "reset-password/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        views.password_updated,
        name="password_reset_complete",
    ),
    # Change passowrd URLs
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path("change-password/done/", views.password_updated, name="password_change_done"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/views.py
from django.shortcuts import redirect


def home(_request):
    return redirect("agendas:home")

def password_updated(_request):
    return redirect("accounts:password_updated")

src/main/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>

<body>
    <h1>This is the about page</h1>
</body>

</html>

src/main/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html class="{{ request.COOKIES.dark_theme }}">

<head>
    {% load django_bootstrap_icons %} {% include_bootstrap_icons %}{% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Agendas</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/8.6.4/jsoneditor.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/styles.css'%}" />
    <!-- <link rel="stylesheet" href="{% static 'css/responsive-font.css'%}" /> -->
    <!-- include summernote css/js -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet" />
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://kit.fontawesome.com/cb8588d293.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/8.6.4/jsoneditor.js" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="{% static 'js/custom-menu.js'%}"></script>

    <!--[if lt IE 7]>
      <p class="browsehappy">
        You are using an <strong>outdated</strong> browser. Please
        <a href="#">upgrade your browser</a> to improve your experience.
      </p>
    <![endif]-->
    {% load navigation %} {% navigation %}{% load side_menu %}{% side_menu %}
    <div class="container">{% block content %}{% endblock %}</div>

    <script>
        var x = document.querySelectorAll("input:not([type='submit']),select,textarea");
        for (var i = 0; i < x.length; i++) {
            if (x[i].type === "file") {
                x[i].classList.add(".form-control-file");
            } else if (x[i].type === "checkbox") {} else {
                x[i].classList.add("form-control");
            }
        }
    </script>
    <script>
        function customSort(sortName, sortOrder, data) {
            var order = sortOrder === "desc" ? -1 : 1;
            data.sort(function(a, b) {
                var aa = +(a[sortName] + "").replace(/[^\d]/g, "");
                var bb = +(b[sortName] + "").replace(/[^\d]/g, "");
                if (aa < bb) {
                    return order * -1;
                }
                if (aa > bb) {
                    return order;
                }
                return 0;
            });
        }

        function drag(ev) {
            console.log("ev", ev);
            ev.dataTransfer.setData("text", ev.target.innerHTML);
        }

        $("<div id='header_list' class=''></div>").insertAfter("#id_headers");
        $("#id_headers option").sort().each(function() {
            if ($(this).text() != "---") {
                $("#header_list").append(
                    `<div class="text-light px-2 py-1 badge bg-secondary m-1" draggable="true" ondragstart="drag(event)" >${$(
              this
            )
              .text()}</div>`
                );
            }
        });
        $("#id_headers").addClass("d-none");
    </script>
</body>

</html>

src/main/templates/base_form.html
{% load static %}{% block form %} {% csrf_token %} {{form.media}} {{form.non_field_errors }} {% for input in form%}
<div class="form-group p-3 {{input.name}}">
  {{input.label_tag}} {{input|safe}} {{input.errors}}
</div>
{% endfor %}
<div class="form-group row">
  <input
    class="col-12 col-md-4 mx-auto mb-2 mb-lg-0"
    type="submit"
    onclick="window.history.back()"
    value="Volver"
  />
  <input
    class="col-12 col-md-4 mx-auto mb-2 mb-lg-0"
    type="submit"
    value="Guardar"
  />
</div>
<script src="{% static 'js/slugify.js' %}"></script>
{% endblock form %}

src/main/templates/navigation.html
{% load django_bootstrap_icons %}
<nav class="navbar navbar-expand-lg shadow mb-2">
  <div class="container">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"><i class="bi bi-list"></i></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav w-100">
        <li
          class="rounded nav-item {% if 'agendas' in request.path %}bg-secondary{% endif %}"
        >
          <a
            class="navbar-brand mx-3 {% if 'agendas' in request.path %}text-white {% endif %}"
            href="{% url 'agendas:home' %}"
            >Agendas</a
          >
        </li>
        <li
          class="rounded nav-item {% if 'models' in request.path %}bg-secondary{% endif %}"
        >
          <a
            class="navbar-brand mx-3 {% if 'models' in request.path %}text-white{% endif %}"
            href="{% url 'templates:home' %}"
            >Modelos</a
          >
        </li>
        <li
          class="rounded nav-item {% if 'sender' in request.path %}bg-secondary{% endif %}"
        >
          <a
            class="navbar-brand mx-3 {% if 'sender' in request.path %}text-white{% endif %}"
            href="{% url 'sender:form' %}"
            >Crear mensaje</a
          >
        </li>
        <li class="form-check form-switch d-flex ms-lg-auto">
          <i class="bi bi-sun"></i>
          <input
            class="mx-1 form-check-input my-auto"
            type="checkbox"
            role="switch"
            id="theme-selector"
          />
          <i class="bi bi-moon"></i>
        </li>
        <li class="rounded nav-item dropdown text-lg-center col-lg-2 mx-3">
          {% if request.user.is_authenticated %}
          <a
            class="navbar-brand dropdown-toggle"
            href="#"
            id="navbarDropdownMenuLink"
            data-bs-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            {{request.user}}
          </a>
          <div
            class="dropdown-menu mt-2 w-100 shadow text-lg-center"
            style="min-width: auto"
            aria-labelledby="navbarDropdownMenuLink"
          >
            <div class="dropdown-item p-0 text-wrap">
              <a class="btn" href="{% url 'password_change' %}">
                Cambiar contraseña
              </a>
            </div>

            {% if request.user.is_superuser %}
            <div class="dropdown-item p-0">
              <a class="btn" href="{% url 'admin:index' %}">Administrar</a>
            </div>
            {% endif %}
            <form
              class="dropdown-item p-0"
              action="{% url 'accounts:logout' %}"
              method="post"
            >
              {% csrf_token %}
              <input class="btn" type="submit" value="Desconectar" />
            </form>
          </div>
          {% else %}

          <div class="d-flex">
            <form
              class="form-inline my-2 my-lg-0"
              action="{% url 'accounts:login' %}"
              method="get"
            >
              {% csrf_token %}
              <input class="btn" type="submit" value="Iniciar sesion" />
            </form>

            <form
              class="form-inline my-2 my-lg-0"
              action="{% url 'accounts:register' %}"
              method="get"
            >
              {% csrf_token %}
              <input class="btn" type="submit" value="Registrarse" />
            </form>
          </div>
          {% endif %}
        </li>
      </div>
    </div>
  </div>
</nav>
<script>
  function getCookie(cname) {
    let name = cname + "=";
    let decodedCookie = decodeURIComponent(document.cookie);
    let ca = decodedCookie.split(";");
    for (let i = 0; i < ca.length; i++) {
      let c = ca[i];
      while (c.charAt(0) == " ") {
        c = c.substring(1);
      }
      if (c.indexOf(name) == 0) {
        return c.substring(name.length, c.length);
      }
    }
    return "";
  }
  const btn = document.querySelector("#theme-selector");
  const theme = document.querySelector("html");
  if (getCookie("dark_theme") === "dark-theme") {
    btn.checked = true;
  } else if (
    getCookie("dark_theme") !== "light-theme" &&
    window.matchMedia("(prefers-color-scheme: dark)").matches
  ) {
    theme.className = "dark-theme";
    btn.checked = true;
  }
  btn.addEventListener("click", function () {
    document.cookie =
      theme.className === "dark-theme"
        ? "dark_theme=light-theme;path=/"
        : "dark_theme=dark-theme;path=/";
    theme.className =
      theme.className === "dark-theme" ? "light-theme" : "dark-theme";
  });
</script>

src/main/templates/side_menu.html
{% if menu_title %}
<button
  class="btn offcanvas-toggle shadow"
  type="button"
  data-bs-toggle="offcanvas"
  data-bs-target="#sidebar"
  aria-controls="sidebar"
  title="Abrir menu {{menu_title |lower}}"
>
  <i class="bi bi-caret-right"></i>
</button>
<div
  class="offcanvas offcanvas-start"
  tabindex="-1"
  id="sidebar"
  aria-labelledby="sidebarLabel"
>
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="sidebarLabel">{{menu_title}}</h5>
    {% if menu_type == 'agenda' %}
    <form class="form-inline" action="{% url 'agendas:form' %}">
      <button class="btn btn-sm rounded shadow">
        <i class="bi bi-plus"></i>Nueva agenda
      </button>
    </form>
    {% elif menu_type == 'plantilla' %}
    <form class="form-inline" action="{% url 'templates:form' %}">
      <button class="btn rounded shadow">
        <i class="bi bi-plus"></i> Nuevo modelo
      </button>
    </form>
    {% endif %}
    <button
      type="button"
      class="btn btn-circle btn-sm shadow"
      data-bs-dismiss="offcanvas"
      aria-label="Close"
    >
      <i class="bi bi-caret-left"></i>
    </button>
  </div>
  <div class="offcanvas-body">
    <ul class="navbar-nav row">
      {% for item in menu_items %}
      <div class="nav-item">
        {% if menu_type == 'agenda' %}
        <a
          class="nav-link"
          href="{% url 'agendas:category.form' category=item.label.slug %}"
        >
          {{ item.label.title }}
        </a>
        {% elif menu_type == 'plantilla' %}
        <a
          class="nav-link"
          href="{% url 'templates:category.form' category=item.label.slug %}"
        >
          {{ item.label.title }}
        </a>

        {% endif %}
        <div class="">
          {% for val in item.value %} {% if menu_type == 'agenda' %}
          <li>
            <a
              class="dropdown-item"
              href="{% url 'agendas:detail' slug=val.slug %}"
              >{{ val.year }} {{ val.title }}</a
            >
          </li>
          {% elif menu_type == 'plantilla' %}
          <li>
            <a
              class="dropdown-item"
              href="{% url 'templates:detail' slug=val.slug %}"
              >{{ val.year }} {{ val.title }}
            </a>
          </li>
          {% endif %} {% endfor %}
        </div>
      </div>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
</div>
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>