src/agendas/urls.py
from django.urls import path, include
from . import views

app_name = "agendas"
urlpatterns = [
    # path("agendas/", views.get_agendas, name="list"),
    path("", views.agenda_detail, name="home"),
    # path("categories/", views.categories, name="categoreis"),
    path("categories/form/", views.category_form, name="category.form"),
    path("categories/form/<slug:category>", views.category_form, name="category.form"),
    path(
        "categories/delete/<str:category_id>",
        views.deleteCategory,
        name="category.delete",
    ),
    path("form/", views.agenda_form, name="form"),
    path("form/<slug:slug>", views.agenda_form, name="form"),
    path("<slug:slug>", views.agenda_detail, name="detail"),
    path(
        "<slug:slug>/import", include(("importer.urls", "home"), namespace="importer")
    ),
    path("<slug:slug>/contacts/", include("contacts.urls")),
    path("delete/<str:agenda_id>", views.delete, name="delete"),
]

src/contacts/urls.py
from django.urls import path
from . import views

app_name = "contacts"

urlpatterns = [
    # path('', views.contact_list, name="list"),
    path('form', views.contact_form, name="form"),
    path('form/<str:contact_id>', views.contact_form, name="form"),
    # path('<str:contact_id>', views.contact_detail, name="detail"),
    path('delete/<str:contact_id>', views.delete, name="delete")
]

src/mailsender/urls.py
from django.urls import path
from . import views

app_name = "sender"

urlpatterns = [
    # path('history/', views.history, name="list"),
    path('', views.form, name="form"),
    # path('<str:broadcast>', views.form, name="form"),
    # path('success/<str:broadcast>', views.success, name="success"),
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("import/", include("importer.urls")),
    path("models/", include("mailtemplates.urls")),
    path("sender/", include("mailsender.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("agendas/", include("agendas.urls")),
    path("", views.home),
    # Forgot password URLS
    path(
        "reset-password/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "reset-password/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        views.password_updated,
        name="password_reset_complete",
    ),
    # Change passowrd URLs
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path("change-password/done/", views.password_updated, name="password_change_done"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/agendas/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db.models.functions import datetime


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name="Nombre")
    slug = models.SlugField(verbose_name="URL", unique=True)

    def __str__(self):
        return self.title


class Agenda(models.Model):
    title = models.CharField(max_length=199, default="", verbose_name="Título")
    slug = models.SlugField(default="", unique=True, verbose_name="URL amigable")
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name="Categoría",
    )
    year = models.year = models.IntegerField(
        default=datetime.timezone.now().year,
        validators=[MinValueValidator(1970), MaxValueValidator(9999)],
        verbose_name="Año",
    )
    creation_date = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.year) + "-" + str(self.category) + "-" + self.title

src/agendas/forms.py
from django import forms
from .models import Agenda, Category
from django.utils.text import slugify


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["title", "slug"]


class AgendaForm(forms.ModelForm):
    new_category_title = forms.CharField(required=False, label="Nueva categoría")
    slug = forms.CharField(required=False)

    class Meta:
        model = Agenda
        fields = ["title", "year", "category", "new_category_title", "slug"]

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        category = cleaned_data.get("category")
        new_category_title = cleaned_data.get("new_category_title")
        year = cleaned_data.get("year")

        # If a new category title is provided, create a new category and use it for the agenda
        if title:
            if Agenda.objects.filter(title=title).exists():
                self.add_error(
                    "title", "Ya existe una agenda con este nombre."
                )
            elif Agenda.objects.filter(slug=slugify(title)).exists():
                self.add_error(
                    "title",
                    "Ya existe una agenda con el slug generado a partir de este nombre.",
                )
            else:
                slug = slugify(f'{category}-{year}-{title}')
                cleaned_data["slug"] = slug

        # If a new category title is provided, create a new category and use it for the agenda
        if new_category_title and not category:
            if Category.objects.filter(title=new_category_title).exists():
                self.add_error(
                    "new_category_title", "Ya existe una categoria con este nombre."
                )
            elif Category.objects.filter(slug=slugify(new_category_title)).exists():
                self.add_error(
                    "new_category_title",
                    "Ya existe una categoria con el slug generado a partir de este nombre.",
                )
            else:
                slug = slugify(new_category_title)
                category = Category.objects.create(title=new_category_title, slug=slug)
                cleaned_data["category"] = category

        # If no category is selected and no new category title is provided, raise a validation error
        elif not category:
            self.add_error(
                "category", "Please select an existing category or create a new one."
            )

        return cleaned_data

src/agendas/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.shortcuts import render, redirect
from .models import Agenda, Category
from contacts.models import Contact
from . import forms
from importer.forms import UploadFileForm
from importer.importer import extract_headers
from .forms import AgendaForm

# Get an instance of a logger
import logging

logger = logging.getLogger("logging.StreamHandler")


def categories(request):
    categories = Category.objects.all()
    return render(
        request, "agendas/categories/categories_list.html", {"categories": categories}
    )


# def agenda_list(request):
#     category = request.GET.get("category") or None
#     if category:
#         category = Category.objects.get(slug=category)
#         agendas = Agenda.objects.filter(category=category.id).order_by("year")

#         return render(
#             request,
#             "agendas/agendas_list.html",
#             {"agendas": agendas, "category": category},
#         )
#     else:
#         agendas = Agenda.objects.all()
#     return render(request, "agendas/agendas_list.html", {"agendas": agendas})

# def get_agendas(request):
#     agendas = Agenda.objects.all()
#     # serializer = AgendaSerializer(agendas, many=True)
#     # return JsonResponse(serializer.data, safe=False)
#     return render(request, "agendas/agendas_list.html", {"agendas":agendas})


@login_required
@staff_member_required(login_url="accounts:staff_only")
def agenda_detail(request, slug=None):
    agenda = Agenda.objects.get(slug=slug) if slug else None
    contacts = (
        [model_to_dict(contact) for contact in Contact.objects.filter(agenda=agenda)]
        if slug
        else [model_to_dict(contact) for contact in Contact.objects.all()]
    )
    menu_items = [
        {"label": cat, "value": [ag for ag in Agenda.objects.filter(category=cat)]}
        for cat in Category.objects.all()
    ]
    form = UploadFileForm()
    headers = extract_headers(contacts)
    return render(
        request,
        "agendas/agendas_detail.html",
        {
            "agenda": agenda,
            "contact_list": contacts,
            "form": form,
            "headers": headers,
            "len_headers": len(headers),
            "menu_items": menu_items,
            "menu_title": "Agendas",
            "menu_type": "agenda",
        },
    )


@login_required
@staff_member_required(login_url="accounts:staff_only")
def agenda_form(request, slug=""):
    agenda = Agenda.objects.get(slug=slug) if slug else None
    if request.method == "POST":
        form = AgendaForm(request.POST or None, instance=agenda)
        if form.is_valid():
            form.save()
            return redirect("agendas:detail", slug=form.instance.slug)
    else:
        form = AgendaForm(initial=model_to_dict(agenda) if agenda else None)

    return render(
        request,
        "agendas/agendas_form.html",
        {"agenda": agenda, "form": form},
    )


@login_required
@staff_member_required(login_url="accounts:staff_only")
def category_form(request, category=""):
    category = Category.objects.get(slug=category) if category else None
    logger.info("form")
    if request.method == "POST":
        logger.info("POST form")
        form = forms.CategoryForm(request.POST or None, instance=category)
        logger.info(form)
        if form.is_valid():
            category_instance = form.save(commit=False)
            category_instance.save()
            return redirect("agendas:home")
    else:
        form = forms.CategoryForm(initial=model_to_dict(category) if category else None)
    return render(
        request,
        "agendas/categories/categories_form.html",
        {"category": category, "form": form},
    )


@login_required
@staff_member_required(login_url="accounts:staff_only")
def deleteCategory(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    return redirect("agendas:home")


@login_required
@staff_member_required(login_url="accounts:staff_only")
def delete(request, agenda_id):
    agenda = Agenda.objects.get(id=agenda_id)
    agenda.delete()
    return redirect("agendas:home")

src/agendas/templates/agendas/agenda_detail.html
{% extends 'header.html' %}{% load django_bootstrap_icons %} {% block content %}

<div class="agenda">
    <div class="agenda">
        <h2>{{agenda.title}}-{{agenda.year}}</h2>
        <p>Created on: {{agenda.creation_date}}</p>
    </div>
    <div class="contacts">
        {% include "contacts/table.html" with contacts=contact_list headers=headers %}

        <div class="form-group row">
            {% include 'importer/form.html' %}
            <form class="form-inline col-12 col-md-4 mx-auto" action="{% url 'contacts:form' %}">
                <button class="btn bg-white shadow col-12 ">{% bs_icon 'plus-circle-fill' extra_classes='text-success'%}&nbsp;&nbsp;Añadir Contacto</button>
            </form>
        </div>
    </div>
    {% endblock content %}

src/agendas/templates/agendas/agenda_form.html
{% extends 'header.html' %} {% block content %}
<div class="container">
    {% if agenda %}
    <h2 class="">Editar Agenda</h2>
    <form class="site-form " action="{% url 'agendas:form' agenda_id=agenda.id %}" method="post" enctype="multipart/form-data">
        {% else %}
        <h2 class="">Crear Agenda</h2>
        <form class="site-form " action="{% url 'agendas:form' agenda_id='new' %}" method="post" enctype="multipart/form-data">
            {% endif %} {% csrf_token %} {{ form.non_field_errors }} {% for input in form%}
            <div class="form-group">
                {{input.label_tag}} {{input}} {{input.errors}}
            </div>
            {% endfor %}
            <div class="form-group">{% if agenda %}
                <input class="form-control" type="submit" value="Editar Agenda"> {% else %}
                <input class="form-control" type="submit" value="Crear Agenda"> {% endif %}
            </div>
        </form>
</div>
<!-- <script src={ % static "js/slugify.js" %}></script> -->
{% endblock content %}

src/agendas/templates/agendas/agendas.html
{% extends 'header.html' %} {% block content %}{% load django_bootstrap_icons %} {% for agenda in agendas %}
<div class="agenda">
    <h2><a href="{% url 'agendas:detail' slug=agenda.slug %}">{{agenda.title}}-{{agenda.year}}</a></h2>
</div>
{% endfor %}

<div class="form-group row">
    <form class="form-inline col-12 col-md-3 mx-auto" action="{% url 'agendas:form' %}">
        <button class="btn bg-white shadow col-12 ">{% bs_icon 'plus-circle-fill' extra_classes='text-success'%}&nbsp;&nbsp;Añadir Agenda</button>
    </form>
</div>
{% endblock %}

src/agendas/templates/agendas/agendas_detail.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block content %}

<div class="container p-4 my-4 shadow rounded">
  <div class="agenda p-3">
    {% if agenda %}
    <div class="row">
      <h3 class="col-auto mx-2">{{agenda.title}}</h3>
      <p class="col-auto mx-2 my-auto">{{agenda.category}}</p>
      <p class="col-auto mx-2 my-auto">{{agenda.year}}</p>
      <p class="col-auto mx-2 my-auto">
        Agenda creada el {{agenda.creation_date}}
      </p>

      <div class="col-auto ms-auto my-auto">
        <form
          class="form-inline"
          action="{% url 'agendas:form' slug=agenda.slug %}"
        >
          <button class="btn shadow ml-auto">
            <i class="bi bi-pencil-square text-success"></i>
            &nbsp;&nbsp;Editar Agenda
          </button>
        </form>
      </div>
    </div>
    {% endif %}
  </div>
  <div class="contacts">
    {% include "contacts/table.html" with title="Contactos" contacts=contact_list headers=headers %} 
    {% if agenda %}
    <div class="form-group row">
      {% include 'importer/form.html' %}
      <form
        class="form-inline col-12 col-md-4 mx-auto mb-2 mb-lg-0"
        action="{% url 'agendas:contacts:form' slug=agenda.slug %}"
      >
        <button class="btn shadow col-12">
          <i class="bi bi-plus-circle-fill text-success"></i>&nbsp;&nbsp;Añadir
          Contacto
        </button>
      </form>
      <form
        class="form-inline col-12 col-md-4 mx-auto mb-2 mb-lg-0"
        action="{% url 'sender:form' %}"
        method="POST"
      >
        {% csrf_token %}
        <input type="hidden" name="agenda" value="{{agenda.slug}}" />
        <input type="hidden" name="imported" value="Importar" />
        <button class="btn shadow col-12">
          <i class="bi bi-envelope text-success"></i>&nbsp;&nbsp;Broadcast
        </button>
      </form>
    </div>
    {% endif %}
  </div>
  {% endblock content %}
</div>

src/agendas/templates/agendas/agendas_form.html
{% extends 'base.html' %} {% block content %}
<div class="container shadow my-4 p-4">
  {%if agenda %}
  <h2>Editar agenda</h2>
  <a
    href="#"
    onclick="if(confirm('¡Atención! ¿Desea borrar la agenda {{agenda.title}} y sus contactos asociados?'))
{location.href='{% url 'agendas:delete' agenda_id=agenda.id %}'}"
    >Borrar agenda</a
  >
  {% else %}
  <h2>Crear agenda</h2>
  {% endif %}
  <form
    class="site-form"
    action=" {% if agenda %}{% url 'agendas:form' slug=agenda.slug %} {% else %} {% url 'agendas:form'  %} {% endif %}"
    method="post"
    enctype="multipart/form-data"
  >
    {% include "base_form.html" %}
  </form>
</div>
<!-- <script src={ % static "js/slugify.js" %}></script> -->
{% endblock content %}

src/agendas/templates/agendas/agendas_list.html
{% extends 'base.html' %} {% block content %}{% load django_bootstrap_icons %}
<div class="container p-4 my-4 shadow rounded">
    {% if category %}
    <h2 class="my-3 display-4">Agendas en categoría: {{category.title}}</h2>
    {% else %}
    <h2 class="my-3 display-4">Todas las agendas</h2>
    {% endif %}{% if agendas %} {% for agenda in agendas %}

    <div class="agenda row">

        <div class="dropdown">
            <a class="dropdown-toggle badge" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% bs_icon 'three-dots-vertical' extra_classes='text-primary mx-2'%}</a>
            <ul class="dropdown-menu text-center" aria-labelledby="navbarDropdownMenuLink">
                <li class="btn" onclick="location.href='{% url 'agendas:detail' slug=agenda.slug %}';">Ver {% bs_icon 'eye' extra_classes='text-primary mx-2'%}</li>
                <li class="btn" onclick="location.href='{% url 'agendas:form' slug=agenda.slug %}';">Editar {% bs_icon 'pencil-square' extra_classes='text-success mx-2'%}</li>
                <li class="btn" onclick="if(confirm('¡Atención! ¿Desea borrar la agenda {{agenda.title}} y sus contactos asociados?'))
                {location.href='{% url 'agendas:delete' agenda_id=agenda.id %}'; alert('agenda borrada');}">Borrar {% bs_icon 'trash' extra_classes='text-danger mx-2'%}</li>
            </ul>
        </div>
        <h4><a class="lead" href="{% url 'agendas:detail' slug=agenda.slug %}">{{agenda.year}} - {{agenda.title}}</a></h4>
    </div>
    {% endfor %} {% else %} No se han encontrado agendas {% endif %}
    <div class="form-group row">
        <form class="form-inline col-auto mx-auto mt-3" action="{% url 'agendas:form' %}">
            <input type="hidden" name="category" value="{{category.slug}}">
            <button class="btn shadow col-12 mx-3 ">{% bs_icon 'plus-circle-fill' extra_classes='text-success'%}&nbsp;&nbsp;Nueva Agenda</button>
        </form>
    </div>
</div>
{% endblock %}

src/agendas/templates/agendas/detail.html
<!DOCTYPE html> {% extends 'base.html' %}{% load django_bootstrap_icons %} {% block content %}

<div class="container p-4 my-4 shadow rounded">
    <div class="agenda p-3">
        {% if agenda %}
        <div class="row">
            <h3 class="col-auto mx-2">{{agenda.title}}</h3>
            <p class="col-auto mx-2 my-auto">{{agenda.category}}</p>
            <p class="col-auto mx-2 my-auto">{{agenda.year}}</p>
            <p class="col-auto mx-2 my-auto"> Agenda creada el {{agenda.creation_date}}</p>

            <div class="col-auto ms-auto my-auto">
                <form class="form-inline" action="{% url 'agendas:form' slug=agenda.slug %}">
                    <button class="btn shadow ml-auto">{% bs_icon 'pencil-square' extra_classes='text-success'%}&nbsp;&nbsp;Editar Agenda</button>
                </form>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="contacts">
        {% include "contacts/table.html" with title="Contactos" contacts=contact_list headers=headers %} {% if agenda %}
        <div class="form-group row">
            {% include 'importer/form.html' %}
            <form class="form-inline col-12 col-md-4 mx-auto" action="{% url 'agendas:contacts:form' slug=agenda.slug %}">
                <button class="btn shadow col-12 ">{% bs_icon 'plus-circle-fill' extra_classes='text-success'%}&nbsp;&nbsp;Añadir Contacto</button>
            </form>
            <form class="form-inline col-12 col-md-4 mx-auto" action="{% url 'sender:form' %}" method="GET">
                <input type="hidden" name="agenda" value="{{agenda.slug}}" />
                <button class="btn shadow col-12 ">{% bs_icon 'envelope' extra_classes='text-success'%}&nbsp;&nbsp;Broadcast</button>
            </form>
        </div>
        {% endif %}
    </div>
    {% endblock content %}

src/agendas/templates/agendas/form.html
{% extends 'base.html' %} {% block content %}
<div class="container shadow my-4 p-4">
    <h2>{{agenda|yesno:"Editar,Crear"}} agenda</h2>
    <form class="site-form " action=" {% if agenda %}{% url 'agendas:form' slug=agenda.slug %} {% else %} {% url 'agendas:form'  %} {% endif %}" method="post" enctype="multipart/form-data">
        {% include "base_form.html" %}
    </form>
</div>
<!-- <script src={ % static "js/slugify.js" %}></script> -->
{% endblock content %}

src/agendas/templates/agendas/list.html
{% extends 'base.html' %} {% block content %}{% load django_bootstrap_icons %}
<div class="container p-4 my-4 shadow rounded">
    {% if category %}
    <h2 class="my-3 display-4">Agendas en categoría: {{category.title}}</h2>
    {% else %}
    <h2 class="my-3 display-4">Todas las agendas</h2>
    {% endif %}{% if agendas %} {% for agenda in agendas %}

    <div class="agenda row">

        <div class="dropdown">
            <a class="dropdown-toggle badge" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% bs_icon 'three-dots-vertical' extra_classes='text-primary mx-2'%}</a>
            <ul class="dropdown-menu text-center" aria-labelledby="navbarDropdownMenuLink">
                <li class="btn" onclick="location.href='{% url 'agendas:detail' slug=agenda.slug %}';">Ver {% bs_icon 'eye' extra_classes='text-primary mx-2'%}</li>
                <li class="btn" onclick="location.href='{% url 'agendas:form' slug=agenda.slug %}';">Editar {% bs_icon 'pencil-square' extra_classes='text-success mx-2'%}</li>
                <li class="btn" onclick="if(confirm('¡Atención! ¿Desea borrar la agenda {{agenda.title}} y sus contactos asociados?'))
                {location.href='{% url 'agendas:delete' agenda_id=agenda.id %}'; alert('agenda borrada');}">Borrar {% bs_icon 'trash' extra_classes='text-danger mx-2'%}</li>
            </ul>
        </div>
        <h4><a class="lead" href="{% url 'agendas:detail' slug=agenda.slug %}">{{agenda.year}} - {{agenda.title}}</a></h4>
    </div>
    {% endfor %} {% else %} No se han encontrado agendas {% endif %}
    <div class="form-group row">
        <form class="form-inline col-auto mx-auto mt-3" action="{% url 'agendas:form' %}">
            <input type="hidden" name="category" value="{{category.slug}}">
            <button class="btn shadow col-12 mx-3 ">{% bs_icon 'plus-circle-fill' extra_classes='text-success'%}&nbsp;&nbsp;Nueva Agenda</button>
        </form>
    </div>
</div>
{% endblock %}